Added NTLM-Authentication-Support
magnuswatn/certsrv pull request #5
Opened 2017-08-09 12:47 UTC by ma44in

This pull-request adds NTLM-Authentication support. Therefore I've refactored the script a little bit and added the function get_response() which handles the HTTP-Request and Response in one single function. 

To use NTLM authentication python module python-ntlm 1.1.0 is required.

2017-08-10 18:28 UTC, magnuswatn commented
Thanks for this! I will look closer at it and provide comments on Saturday.

2017-08-12 13:40 UTC, magnuswatn requested changes
Overall this looks promising, I like the refactoring. I left some comments on the code on things that needs to be addressed.

Thanks again for this!

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +import pprint
Theese doesn't seem to be used. Should probably be removed.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +def get_response(username, password, url, data, auth_method='basic'):
As this function is internal, the name should start with a underscore. _get_response

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +      auth_handler.add_password(realm='My Realm', uri=url, user=username, passwd=password)
I'm not a huge fan of using the HTTPBasicAuthHandler, as it requires a 401 challenge before it will send the credentials. That means doubling the amount of HTTP requests that we need to do. Also, I had to change the realm here to match my IIS server to get to work.

I suggest just adding the header ourself, as was done earlier.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +            raise RequestDeniedException('HTTP Error Code: %s' % response.getcode(), response)
This will only catch success codes than 200, as urllib2 will throw an exception in the case of 4xx or 5xx errors. I don't know of any case where certsrv will return any such code, and I don't think it's appropriate to throw a RequestDeniedException here anyway. I suggest just removing the try/except here.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    cert_url = 'https://%s/certsrv/certnew.cer?ReqID=CACert&Renewal=%s&Enc=%s' % (server, encoding)
The "renewals" parameter seems to have gotten lost here.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +      raise
The whole point of this function is to return False in case of an authentication failure. That doesn't work now. I suggest reverting this to the way it was.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    response = get_response(username, password, url, data_encoded, auth_method)
There is no "data_encoded" variable here. This should be None.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    cert = get_response(username, password, cert_url, auth_method)
We need to .read() the response here, before returning it.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    chain = get_response(username, password, chain_url, '', auth_method).read()
Same as line 160.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    response = get_response(username, password, url, '', auth_method)
Same as line 160.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +    response = get_response(username, password, cert_url, '', auth_method)
An empty string will result in a POST with an empty body. I suggest using None instead, wich will result in a GET.

2017-08-12 13:40 UTC, magnuswatn commented on certsrv.py
> +      response = get_response(username, password, url, '', auth_method)
Same as line 160.

2017-08-13 08:46 UTC, ma44in commented
Thanks for your nice and helpful comments. I've tried to address all points in my last commit. I've reverted Basic-Auth back to "Authorizaion"-Headers, but I could'nt test it, because it's not enabled in our environment.

2017-08-13 16:45 UTC, magnuswatn approved these changes

2017-08-13 16:46 UTC, magnuswatn commented
The basic auth part worked great! I wrote some tests for the NTLM auth part, and fixed some details. 

It was first now I understood why you checked the response code - I didn't know that the HTTP status handling disappeared when using HTTPNtlmAuthHandler :-) I added such that we throw the same error that urllib does without it.

I'm going to merge this now.

2017-08-13 16:47 UTC, merged